source 'http://rubygems.org'

gem 'rails', '4.2.6'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'mysql2', '~> 0.3.20'
  gem 'bootstrap-sass', '~> 3.3.6'
  gem 'devise'
  gem 'jquery-ui-rails'
  gem 'nested_form_fields'
  gem 'rails4-autocomplete'
  #gem 'bullet', '~> 5.6', '>= 5.6.1'
  
  
end

gem 'foreigner'
gem 'prawn'
gem 'prawn-table'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
